### ISSUE TITLE
Heading Colors in Style Settings 

### ISSUE THREAD

**Issue by Guanine** [thegixo/YueObsidian#2]
Thanks for sharing the awesome looking theme. Everything works great but I can't customize the Heading colors specific to Light or Dark theme. 

For example, when I set Heading colors to #FFFFFF, it works great in dark theme, but it becomes invisible in the light theme. 

It would be great if you can add light and dark color inputs  under
Style Settings > Headings > Hn Color

Thanks again!!

**Comment by GixoXYZ** [comment]
Thank you for your feedback!

I have added what you've asked for to the test branch. To test the changes, please download the "theme.css" file and copy it into <Your Obsidian Vault>.obsidian\themes\Yue. Once you've confirmed that the modifications align with your request, I'll merge it into the main branch later.

Cheers,

**Comment by Guanine** [comment]
Thank you so much for the incredibly quick update! It works perfectly now. 
BTW I really love these Light and Dark color schemes! Very elegant. Thanks again for sharing!!!
